---
- name: configure servers
  hosts: server01:server03
  become: yes
  vars_files:
  - vars.yml

  tasks:  
  - name: Get routing table from device and store in variable
    shell: ip route
    register: routingtable

  - name: display output
    debug: output.stdout_lines